project_id = "kfjndfmbiatymgiczkhw"

[functions.analyze-contract]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.extract-contract-from-doc]
verify_jwt = false